### ISSUE TITLE
Is er interesse in een json bestand zodat alles direct in arduino ide en sloeber kan geladen worden?

### ISSUE THREAD

**Issue by jantje** [Fri3dCamp/badge#1]
Ik wil zo wel een maken maar  als er geen interesse is .....

**Comment by Brubacker** [comment]
Zeer zeker interessant, echter is het op de ESP32 gebaseerd dus moet je wel de juiste [compilers etc installeren](https://github.com/espressif/arduino-esp32).

**Comment by michaelshmitty** [comment]
Ik denk dat je ook PlatformIO zou kunnen gebruiken (https://platformio.org/). Je hebt dan een platformio.ini file waarin alle build informatie staat (target platform, juiste versie van libs etc).
Ik heb het zelf nog niet gebruikt maar ik weet dat het luftdaten.info project platformio gebruikt voor hun stofsensor firmware te bouwen.

Alleszins vlotter dan manueel de arduino IDE te moeten installeren, de esp32 toolchain, de juist versies van de juiste libs etc.

Als ik tijd vind dan wil ik het wel eens bekijken. Altijd al eens willen uitproberen.

**Comment by jantje** [comment]
>Alleszins vlotter dan manueel de arduino IDE te moeten installeren, de esp32 toolchain, de juist versies van de juiste libs etc.

Platformio installatie is niet zoveel makkelijker dan Arduino ide en Sloeber.
Platformio is ook niet open source 
Ik denk/hoop dat het enigste wat mist ieen esp32 json file is. Als dat zo is zorg ik er wel voor

**Comment by michaelshmitty** [comment]
> Platformio installatie is niet zoveel makkelijker dan Arduino ide en Sloeber.

Geen idee, was er net mee begonnen. Ik kijk ook eens naar Sloeber want dat ken ik nog niet.

> Platformio is ook niet open source

"PlatformIO is an open source ecosystem for IoT development" staat nochtans in grote letters op de homepagina https://platformio.org
Ja er is ook een "Plus" versie die misschien niet open source is, maar veel projecten gebruiken zo'n model.

**Comment by Brubacker** [comment]
> Ik denk/hoop dat het enigste wat mist ieen esp32 json file is. Als dat zo is zorg ik er wel voor

Helaas is het niet enkel de json file, maar moet je ook de compiler nog installeren 
Voor Debian / Ubuntu: https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/debian_ubuntu.md
Voor Windows : https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/windows.md
Voor Mac : https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/mac.md

> Platformio installatie is niet zoveel makkelijker dan Arduino ide en Sloeber.

Voor Platformio zijn ook instructies beschikbaar. https://github.com/espressif/arduino-esp32/blob/master/docs/platformio.md

**Comment by michaelshmitty** [comment]
Ok net PlatformIO geïnstalleerd in VS Code, dat ging super vlot. Op 10 minuten tijd had ik een blink example draaien op een wemos esp8266 bordje dat ik hier nog had liggen. Heel de toolchain, compiler en libs werden automatisch gedownload.
Heb ook even naar Sloeber gekeken. Ik heb de indruk dat Eclipse + Sloeber == VS Code (of Atom, maar VS Code is stukken sneller en beter imho) + platformIO. Ik gebruik zelf geen Eclipse maar als ik het goed voor heb kan iets zoals Sloeber er net als platformio voor vscode voor zorgen dat lib dependencies enzo bijgehouden worden. Dat is wel een voordeel t.o.v. de Arduino IDE. Tenzij die ook zoiets ondersteund om lib deps (met de juiste versie) bij te houden.
Op een project als dit met een ESP en nog wat randapparatuur is het misschien wel een goed idee om zo'n dependency lijst mee in de repo bij te houden. Dat maakt het clonen, builden en uploaden mogelijk toch wat vlotter en kunnen mensen sneller aan de slag.

Een build systeem opzetten is niet meteen het tofste werk voor hackers/makers die snel met de badge aan de slag willen.

**Comment by calmera** [comment]
ik ben redelijk wat bezig geweest om de ESP32 aan het werken te krijgen met VSCode, om te beginnen schrijven aan de Fri3d arduino library. To be honest, it is a serious PITA. Als er iemand is die het op zich wil nemen om dit op te zetten/beschrijven/... dan wil ik gerust wel kijken om de micropython lib te porten naar arduino.

**Comment by michaelshmitty** [comment]
Ik heb gisteren VSCode + de PlatformIO plugin gebruikt voor twee ESP8266 gebaseerde bordjes (de Wemos D1 Mini en een Nodemcu) en dat ging erg vlot. Dat was op een vanilla Windows PC waar nog niets van toolchains op stond. PlatformIO download automatisch de nodige toolchain, libraries en tools, inclusief de Arduino library voor de ESP8266.
Ik weet niet of het voor de ESP32 even vlot gaat want ik heb zo geen bordje. Volgens de [PlatformIO website](https://platformio.org/platforms/espressif32) zou die wel goed ondersteund zijn. [Moar docs](http://docs.platformio.org/en/latest/platforms/espressif32.html).

@calmera Ik wil dat graag opzetten en beschrijven. Misschien kan @jantje dan een gids voor Sloeber doen. Dan hebben we een breed gamma aan IDE's / tools om met de badge aan de slag te kunnen.
Om te testen zou ik wel een ESP32 zoals op de badge gebruikt wordt in handen moeten krijgen. Dat moet niet perse de Fri3d Camp badge zijn. Een eenvoudige breakout met usb connectie is ook al goed. Ik ben morgenavond in de Open Garage, misschien kan ik er zo wel aan geraken?

**Comment by calmera** [comment]
@michaelshmitty Sure, anthony heeft nog een wemos ESP32 liggen van mij, vraag hem die even en dan ben je normaal vertrokken.

https://community.platformio.org/t/the-esp32-platformio-is-a-game-changer/3194

lijkt me interessant, maar is ESP-IDF. Mijn ervaring (als je daar al over kan spreken) was voornamelijk met platformio + arduino

**Comment by michaelshmitty** [comment]
@calmera Goed idee, ik check morgen in de garage.

Ik kende de term IDF niet, maar als ik het goed voor heb is dat programmeren voor ESP rechtstreeks met de Espressif SDK, zonder de Arduino library abstractie?
Mijn enige ervaring met de Espressif SDK was voor de ESP8266 in mijn [EsperPass project](https://gitlab.com/shmitty/esperpass) (dat jammer genoeg obsolete is omdat Nintendo de 3DS StreetPass servers uitgezet heeft).
Maar daar gebruikte ik geen IDE voor. Gewoon text editor + de manueel geïnstalleerde toolchain van Espressif. Dat werkte eigenlijk heel vlot, maar niet aan te raden om snel van start te gaan: die build env opzetten is wat complex en moet op een case sensitive filesystem gebeuren. Op mijn mac was dat op te lossen door een sparse volume disk image aan te maken maar ik zou niet weten of dat op Windows zo vanzelfsprekend zou zien.
Moest ik opnieuw aan dat project beginnen zou ik VS Code + PlatformIO gebruiken.

Ik vind persoonlijk het verschil tussen Arduino en rechtstreeks met de SDK werken niet zo'n groot. Maar er zijn veel makers wiens eerste ervaring met C(++) de Arduino library is dus ik vind het zeker een goed idee om dat te ondersteunen voor de badge (naast Python, goed idee!). En ik denk ook wel dat VS Code + PIO dat ondersteunt. Hier is een voorbeeld van een projectje dat ik gisteren in VS Code + PIO heb aangemaakt: https://github.com/michaelshmitty/Blink3
En dat gebruikt de Arduino library bovenop de SDK. En merk op dat bijna de enige extra bestanden de platformio.ini en de optionele travis config voor testing zijn. In die platformio.ini zie je dan het gebruikte platform en de lib dependencies. Dat is wel super handig om iedereen snel dezelfde build environment op te helpen zetten. Zoals cargo.toml in de Rust programmeertaal moest je daar bekend mee zijn. Of de Gemfile in Ruby.
Ik ga ervan uit dat de Arduino library in VS Code + PIO ook gewoon met de ESP32 werkt. Ik probeer het uit zodra ik een ESP32 te pakken heb.

Sorry voor de omwegen op dit thread!
Ik heb al een tijd de Arduino IDE niet meer gebruikt. Is er eigenlijk een manier om in de Arduino IDE de lib dependencies (naam, versie) te specificeren en mee in je git repo te steken?
Ik ga ervan uit dat vele makers ook de Arduino IDE zullen willen gebruiken om met de badge aan de slag te gaan.

**Comment by michaelshmitty** [comment]
@calmera PlatformIO ondersteunt het Arduino framework voor de ESP32: http://docs.platformio.org/en/latest/platforms/espressif32.html#frameworks

**Comment by jantje** [comment]
Deze werkt bij mij in windows 10
https://raw.githubusercontent.com/jantje/arduino-esp32/master/package/package_Espressif_esp32_index.json
Het zou ook moeten werken op andere oses

**Comment by jantje** [comment]
Heeft er al iemand geprobeerd?

**Comment by Brubacker** [comment]
Net een test gedaan op Ubuntu 18.04 LTS x64 met Arduino 1.8.5 x64 en kreeg de melding dat de esptool niet beschikbaar was voor mijn OS.

**Comment by jantje** [comment]
Inderdaad die zit er niet tussen. En met de get krijg je die wel?
Weet jij waar je die kan downloaden?
En de 32 bit versie?

**Comment by jantje** [comment]
Ik vraag dat want zover ik de code begrijp is deze file https://github.com/espressif/arduino-esp32/blob/master/package/package_esp32_index.template.json#L87
de enigste die referenties bevat. En er zit er geen in voor linux. Misschien is de macos ook gebruikt voor linux?

**Comment by Brubacker** [comment]
Ziet er naar uit dat die nog niet werkt : 
https://github.com/espressif/arduino-esp32/issues/515

**Comment by jantje** [comment]
Dit is een json die ik gemaakt heb. Nadat ik gezocht had op een bestaande json en niks vond.
Ik heb ook de platform.txt aangepast  om het te doen werken.
Het werkt ook op windows (bij mij en iemand anders)
Alleen weet ik niet welke esptool er in linux wordt geinstalleerd.
Als je get draaid in linux zie je de naam van de gedownloade bestanden en die zou ik moeten hebben.

**Comment by jantje** [comment]
espresif is in actie geschoten  https://dl.espressif.com/dl/package_esp32_dev_index.json

**Comment by Brubacker** [comment]
Lijkt te werken op Win10 x64 met Arduino 1.8.5

**Comment by jantje** [comment]
En er zijn links voor esptool in linux :-)
Ik denk dat deze issue dan ook kan ggesloten worden tenzij er vraag is voor een fried board met alle opties die geen opties zijn voorgekozen.

**Comment by Brubacker** [comment]
Arduino ontwikkeling in andere repo -> https://github.com/Fri3dCamp/Fri3dBadge
